SELECT * from test1;

--null values
SELECT 
  COUNT(*) AS null_count
FROM TEST1.STREAM.test1
WHERE AGE IS NULL 
   OR GENDER IS NULL 
   OR BMI IS NULL 
   OR DIAGNOSIS IS NULL;

--outliers
SELECT *
FROM TEST1.STREAM.test1
WHERE AGE NOT BETWEEN 50 AND 90
   OR BMI NOT BETWEEN 15 AND 40
   OR SYSTOLICBP NOT BETWEEN 90 AND 180
   OR DIASTOLICBP NOT BETWEEN 60 AND 120
   OR CHOLESTEROLTOTAL NOT BETWEEN 150 AND 300;


--duplicates
SELECT PATIENTID, COUNT(*) AS occurrence
FROM TEST1.STREAM.TEST1
GROUP BY PATIENTID
HAVING COUNT(*) > 1;


--creating cleaned dataset
CREATE OR REPLACE TABLE TEST1.STREAM.TEST1_CLEANED AS
SELECT *
FROM (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY PATIENTID ORDER BY PATIENTID) AS rn
  FROM TEST1.STREAM.TEST1
)
WHERE rn = 1;