CREATE OR REPLACE TABLE TEST1.STREAM.TEST1_FEATUREENG AS
SELECT 
  -- Keep only useful columns, exclude PatientID and DoctorInCharge
  AGE,
  GENDER,
  ETHNICITY,
  EDUCATIONLEVEL,
  BMI,
  BMI_CATEGORY,
  SMOKING,
  ALCOHOLCONSUMPTION,
  PHYSICALACTIVITY,
  DIETQUALITY,
  SLEEPQUALITY,
  FAMILYHISTORYPARKINSONS,
  TRAUMATICBRAININJURY,
  HYPERTENSION,
  DIABETES,
  DEPRESSION,
  STROKE,
  SYSTOLICBP,
  DIASTOLICBP,
  CHOLESTEROLTOTAL,
  CHOLESTEROLLDL,
  CHOLESTEROLHDL,
  CHOLESTEROLTRIGLYCERIDES,
  UPDRS,
  MOCA,
  FUNCTIONALASSESSMENT,
  TREMOR,
  RIGIDITY,
  RISK_SCORE,
  BRADYKINESIA,
  POSTURALINSTABILITY,
  SPEECHPROBLEMS,
  SLEEPDISORDERS,
  CONSTIPATION,
  DIAGNOSIS,
  
  -- naming gender
  CASE 
    WHEN GENDER = 0 THEN 'Male' 
    WHEN GENDER = 1 THEN 'Female' 
    ELSE 'Unknown' 
  END AS GENDER_LABEL,

   CASE 
    WHEN DIAGNOSIS = 0 THEN 'No' 
    WHEN DIAGNOSIS = 1 THEN 'Yes' 
    ELSE 'Unknown' 
  END AS PARKINSON_DIAGNOSIS,

  -- naming education
  CASE 
    WHEN EDUCATIONLEVEL = 0 THEN 'None'
    WHEN EDUCATIONLEVEL = 1 THEN 'High School'
    WHEN EDUCATIONLEVEL = 2 THEN 'Bachelors'
    WHEN EDUCATIONLEVEL = 3 THEN 'Higher'
    ELSE 'Unknown'
  END AS EDUCATION_LABEL,

  -- naming ethnicity
  CASE 
    WHEN ETHNICITY = 0 THEN 'Caucasian'
    WHEN ETHNICITY = 1 THEN 'African American'
    WHEN ETHNICITY = 2 THEN 'Asian'
    WHEN ETHNICITY = 3 THEN 'Other'
    ELSE 'Unknown'
  END AS ETHNICITY_LABEL,

  -- creating age groups
  CASE 
    WHEN AGE BETWEEN 50 AND 59 THEN '50–59'
    WHEN AGE BETWEEN 60 AND 69 THEN '60–69'
    WHEN AGE BETWEEN 70 AND 79 THEN '70–79'
    WHEN AGE >= 80 THEN '80+'
    ELSE 'Unknown'
  END AS AGE_GROUP

FROM TEST1.STREAM.TEST1_TRANSFORMED;