SELECT 
    BMI_CATEGORY,
    GENDER_LABEL,
    COUNT(*) AS diagnosis_count
FROM TEST1.STREAM.TEST1_FEATUREENG
WHERE DIAGNOSIS = 1
GROUP BY BMI_CATEGORY, GENDER_LABEL
ORDER BY BMI_CATEGORY, GENDER_LABEL;