-- copy of the feature engineered table
CREATE OR REPLACE TABLE TEST1_FEATUREENG_COPY AS
SELECT * FROM TEST1_FEATUREENG;

-- Delete
DELETE FROM TEST1_FEATUREENG_COPY WHERE AGE > 35;

-- View the state 5 minutes ago
SELECT COUNT(*) FROM TEST1_FEATUREENG_COPY AT (OFFSET => -60*5);