SELECT 
    GENDER_LABEL,
    EDUCATION_LABEL,
    COUNT(*) AS diagnosis_count
FROM TEST1.STREAM.TEST1_FEATUREENG
WHERE DIAGNOSIS = 1
GROUP BY GENDER_LABEL, EDUCATION_LABEL
ORDER BY GENDER_LABEL, EDUCATION_LABEL;